version: '3'

services:
  db:
    image: postgres
    env_file:
      - .env
    restart: always
    ports:
    - '5432:5432'


  app:
    build: .
    env_file:
      - .env
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    depends_on:
      - db

